### ISSUE TITLE
Thanks & and a question

### ISSUE THREAD

**Issue by b3nis** [deffinmoney/poposonrazerblade152020#4]
Thanks for replying to me on Reddit - now I am here. Great work you have done. I do have one questions what you mean with:
`Once updated you will want to fix the suspend loop issue that you get with this laptop amoung others.`
I had an issue while running Fedora that the computer would think that the lid is closed even tho it's open and it would just go to sleep again and again, super annoying. I had to turn off lid = suspend and sleep it with the button. However, with Pop_OS! - this didn't happen anymore (I have no idea why). However, something that I am experiencing with Pop_OS! is that sometimes when I wake up the computer the wayland session do not resume (just a black screen). So I guess I am wondering what your issues was/is.

Thanks again!

**Comment by deffinmoney** [comment]
Thanks for your interest. the fedora issue would be fixed with grub, let me know if you need the fix i have it for grub, just let me know and I will post it. This is the same type of issue that comes up in Pop. It seems to be hit or miss. Sometimes I will install pop and not have any issues with the suspend loop and most of the time I do. Basically, you would shut the lid and it would go to sleep, then when you open the lid it seems ok but then goes back to sleep. The Kernel stub fix fixes this, so that it behaves like in windows or macos.

**Comment by b3nis** [comment]
Interesting, because I had this issue with Fedora - and I could see that the lid reported as "closed" sometimes and that caused the loop. I thought it was a hardware issue, but then I tried Pop OS and it worked flawless. Weird. However, great with the fix!

**Comment by deffinmoney** [comment]
Thanks, I am happy someone is using it and having success. I spent so long like multiple day on multiple installs to try and find a fix for both of these things. Are you using a razer blade as well? with the new updates to Pop scheduler it works so good now.

**Comment by b3nis** [comment]
I actually switched over to an Asus G14 2022 today due to Linux support for ASUS ROG laptop seems better. But yes, I used to use a Razer Blade 15 Base 2020 as my daily driver.
